### PR TITLE
Remove ActionResultPayload

### PR DESCRIPTION
**Pull request by chrisarcand**
This was replaced by QueueResultPayload and should have been removed in #43

### CODE REVIEW

**Comment by jrafanie** [comment]
🤔 looks like code

**Comment by chrisarcand** [comment]
nice comment @jrafanie well done 👏

**Comment by chrisarcand** [comment]
Also ping @imtayadeway

**Comment by chrisarcand** [comment]
🏓 @imtayadeway

**Review by imtayadeway — APPROVED** [review]

**Pull request merged**
