### PR TITLE
missing babel presets

### PR DESCRIPTION
**Pull request by priley86**
hello ;)

we seemed to have found the following issue when attempting to load the graphql-explorer (webpack'd plugin) alongside the [v2v](https://github.com/priley86/miq_v2v_ui_plugin) (webpack'd plugin):

http://pastebin.test.redhat.com/562325

Adding the following presets seems to resolve this for now...

### CODE REVIEW

**Comment by imtayadeway** [comment]
@priley86 I'm not a JavaScript whizz, but I think I can understand why this is needed. I'm assuming that webpack-dev-server requires everything to be compiled into ES2015, so the dependencies here break? Can you try to verify this and update your commit message to explain why this change is needed, with links to the appropriate areas concerned?

I'm just concerned that this is introducing an implicit dependency on libraries used in the consumer (manageiq-ui-classic) - can this not be handled on the consumer end? If not, an explanation of why would also be a useful thing to add to your commit message.

Thanks!

**Review by AllenBW — APPROVED** [review]
WHAT NO BABEL PRESETS?!

😋 🌮 💃

**Comment by AllenBW** [comment]
OOOooooooOOOooo yeah same concerns as @imtayadeway why is this being included here? why not in wherever webpack is 🤢 ?

**Comment by priley86** [comment]
yup... was addressed in ui-classic earlier...thanks!

**Comment by AparnaKarve** [comment]
@imtayadeway @priley86 I think we do need this after all.

CI is failing in Classic UI - https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/356943688
-- and I think the reason is indeed the babel presets in this repo.

**Comment by priley86** [comment]
yes - i would agree based on last error messaging i was seeing locally. Presets here should line up w/ ui-classic ?

**Comment by imtayadeway** [comment]
@priley86 I'm reopening this as it looks like you're still having issues (I thought this had gone away). I'd like to do something to help put out :fire: - can you update your commit with some details on the *why* part of this PR - specifically what technical reasons require this and why this can't be handled on the consumer end. I understand that this is a cause of pain right now, and I'd be OK with merging this even if it was a temporary workaround, but I don't want to merge anything that no one (including future developers) understands, or will dare to touch again. Thanks!

**Comment by priley86** [comment]
i appreciate this @imtayadeway

as i am understanding, there are various degrees of 🔥 🚒 👨‍🚒 - i really love Node.js / GraphQL and hope we can keep this plugin moving...

I have reworded the commit. you will need those presets to work alongside ui-classics/v2v plugin webpack presets (react and preset-env) and the webpack dev server since we are loading all plugin "packs" together from ui-classic.

We would also need the following to prevent webpack warnings for `.js.flow` files it seems:
https://github.com/ManageIQ/manageiq-ui-classic/pull/3674

Famous last words... "it works fine on my machine"...

**Comment by AparnaKarve** [comment]
@priley86 Thank you so much for looking into this again!

@imtayadeway Just wanted to mention that although https://github.com/ManageIQ/manageiq-ui-classic/pull/3538 fixes the Classic UI failure, we still continue to get the babel preset error when running webpack server locally with this command -
```
NODE_ENV=development ./node_modules/.bin/webpack-dev-server --config ./config/webpack/development.js
```

and hence would need this PR to be merged.

**Review by imtayadeway — APPROVED** [review]
Thanks!

**Comment by AparnaKarve** [comment]
@imtayadeway Thanks for merging! 
When we have a  better fix in ui-classic to handle the babel presets in various plugins from ui-classic itself, we can undo this.

**Pull request merged**
