### PR TITLE
Add babel presets used in .babelrc as yarn devDependencies

### PR DESCRIPTION
**Pull request by himdel**
This is a follow up to https://github.com/ManageIQ/manageiq-graphql/pull/54, which should prevent some people from a failing `update:ui` with

```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/stomsa/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/manageiq-graphql-ce3bd9ed5bef"
```

Cc @Glutexo, @carbonin, @imtayadeway

### CODE REVIEW

**Comment by Fryguy** [comment]
While I don't mind merging to get things working, this feels really hacky.  Why is this necessary, if this repo is not using these libraries?  Or is it?

**Comment by Glutexo** [comment]
I can confirm that this fixes the issue for me.

**Comment by himdel** [comment]
@Fryguy unfortunately it is :( 

It is using them in the sense that babel does need to load those presets to be able to compile the graphql javascript properly.

The ugly part is that it only seems to need them here if it starts compiling here first, if it starts with ui-classic, these are already loaded and won't fail here.

So.. yeah, I'm not thrilled either, but...  the alternative is for each gem to take care of its own JS and only export ES5, or to copy the files to another place before compilation, but losing the ability for plugins to declare their own dependencies.

**Comment by himdel** [comment]
@djberg96 .. Looks like you'll also need this one to be able to run `webpack-dev-server`. (For https://github.com/ManageIQ/manageiq/issues/14347)

**Comment by djberg96** [comment]
👍 Please merge.

**Review by imtayadeway — APPROVED** [review]
I think I might want to review the way things have been separated out as this seems to be causing a lot of issues. Nonetheless, this looks good for now.

**Comment by imtayadeway** [comment]
Thanks @himdel !

**Comment by chrisarcand** [comment]
wat

**Comment by himdel** [comment]
@imtayadeway I kinda agree, seems like trying to do the JS compilation stuff for each plugin from ui-classic seems to bring more problems than expected.

It may make sense to re-evaluate but if we do that, the only way I can come up with is to require each plugin to provider all their external assets in 1 es5 bundle and all the internal assets in another es5 bundle.

So.. essentially copy all the webpack stuff to each plugin.

Right now the only solution that really makes sense to me is to completely separate the new JS code from any rails engine stuff, have a manageiq-ui-classic-javascripts repo which is a npm package (with a travis job to compile any changes to es5 and release them), and have manageiq-ui-classic just require that npm package.

Any ..better ideas? :)

(Well, either that, or make ui-classic the Rails.root, so that we can remove 90% of the crud that handles switching paths and running rake tasks in a different engine.)

**Comment by imtayadeway** [comment]
> Right now the only solution that really makes sense to me is to completely separate the new JS code from any rails engine stuff, have a manageiq-ui-classic-javascripts repo which is a npm package (with a travis job to compile any changes to es5 and release them), and have manageiq-ui-classic just require that npm package.

Sounds interesting!

> (Well, either that, or make ui-classic the Rails.root, so that we can remove 90% of the crud that handles switching paths and running rake tasks in a different engine.)

^^^ This seems to be the core of the problem - the classic UI is *as if* the Rails root - it (and probably most of the other engines) is not a real "engine" - none of the engines should have dependencies on each other. If we need to build APIs for engines to depend on, maybe they should be in core? It might be good to have a more lengthy conversation about this some time.

**Pull request merged**
