### PR TITLE
Bump to ruby 2.3.6

### PR DESCRIPTION
**Pull request by jrafanie**
Bump to ruby 2.3.6

### CODE REVIEW

**Comment by chrisarcand** [comment]
@jrafanie Was SCL updated? Doesn't look like it...? Or changing Travis policy on that?

**Comment by jrafanie** [comment]
It should be at some point soon since it was changed to 2.3.6 in rhel land

**Comment by chrisarcand** [comment]
:shipit:

**Review by imtayadeway — APPROVED** [review]
:heart:

**Pull request merged**
