### PR TITLE
Add plugin display name

### PR DESCRIPTION
**Pull request by mzazrivec**
See ManageIQ/manageiq-ui-classic#4496 for primary motivation.

### CODE REVIEW

**Comment by chrisarcand** [comment]
Move the class method you wrote above any instance methods (`vmdb_plugin?`) please.

**Comment by mzazrivec** [comment]
@chrisarcand fixed.

**Comment by chrisarcand** [comment]
Heh, I think I lost write access since last week :)

I leave you in the loving hands of @Fryguy 💕

**Comment by Fryguy** [comment]
@mzazrivec If this needs to come back to hammer, can you set the labels?

**Comment by mzazrivec** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 5751b531db8111d4c18a23f2d04131e03d59712f
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Oct 16 09:40:25 2018 -0400

    Merge pull request #60 from mzazrivec/add_plugin_name
    
    Add plugin display name
    
    (cherry picked from commit cedc0a4b6386770cdacddd0a90081e5b85db4758)
```

**Pull request merged**
